version: "3.9"
services:
  surrealdb:
    image: surrealdb/surrealdb:latest
    command: start --log info --user root --pass root --bind 0.0.0.0:8080
    volumes:
      - surrealdb_data:/data
    networks:
      - backend_network

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.prod
    depends_on:
      - surrealdb
    environment:
      DATABASE_URL: "ws://surrealdb:8080"
      ROCKET_ADDRESS: "0.0.0.0"
      ROCKET_PORT: "80"
    ports:
      - "80:80"
    networks:
      - backend_network

volumes:
  surrealdb_data:

networks:
  backend_network:
    driver: bridge